# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import s3direct.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('image', s3direct.fields.S3DirectField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Motive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='motive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Motive'),
        ),
    ]
