# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-07 15:39
from __future__ import unicode_literals

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='image',
            field=s3direct.fields.S3DirectField(blank=True, null=True),
        ),
    ]
