# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
