# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 23:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import s3direct.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('budget', models.FloatField()),
                ('budget_spent', models.FloatField(default=0)),
                ('image', s3direct.fields.S3DirectField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatusCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='End',
            fields=[
                ('statuscampaign_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='campaign.StatusCampaign')),
            ],
            bases=('campaign.statuscampaign',),
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('statuscampaign_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='campaign.StatusCampaign')),
            ],
            bases=('campaign.statuscampaign',),
        ),
        migrations.CreateModel(
            name='WaitingPay',
            fields=[
                ('statuscampaign_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='campaign.StatusCampaign')),
            ],
            bases=('campaign.statuscampaign',),
        ),
        migrations.CreateModel(
            name='Working',
            fields=[
                ('statuscampaign_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='campaign.StatusCampaign')),
            ],
            bases=('campaign.statuscampaign',),
        ),
        migrations.AddField(
            model_name='campaign',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.StatusCampaign'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
