# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-22 13:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('budget', models.FloatField()),
                ('budget_spent', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('spend', models.FloatField()),
                ('impressions', models.IntegerField()),
                ('clicks', models.IntegerField()),
                ('sign_ups', models.IntegerField()),
                ('conversion', models.IntegerField()),
                ('revenues', models.FloatField()),
                ('ads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.Ads')),
            ],
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StatusCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Delete',
            fields=[
                ('statuscampaign_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='campaign.StatusCampaign')),
            ],
            bases=('campaign.statuscampaign',),
        ),
        migrations.CreateModel(
            name='End',
            fields=[
                ('statuscampaign_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='campaign.StatusCampaign')),
            ],
            bases=('campaign.statuscampaign',),
        ),
        migrations.CreateModel(
            name='Working',
            fields=[
                ('statuscampaign_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='campaign.StatusCampaign')),
            ],
            bases=('campaign.statuscampaign',),
        ),
        migrations.AddField(
            model_name='campaign',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='campaign.StatusCampaign'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ads',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.Campaign'),
        ),
        migrations.AddField(
            model_name='ads',
            name='social_network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.SocialNetwork'),
        ),
    ]
