# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-27 13:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170321_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='company',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='plan',
        ),
    ]
