# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-27 14:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170327_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='free',
            name='plan_ptr',
        ),
        migrations.RemoveField(
            model_name='premium',
            name='plan_ptr',
        ),
        migrations.DeleteModel(
            name='Free',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='Premium',
        ),
    ]
